#!/bin/bash

DIR="."	# modificare per scegliere il nome della cartella di destinazione
NAME="tesi"		# modificiare per scegliere il nome del file di origine (.tex)
FINALNAME="TesiMDP"

if [ ! -d $DIR ];
  then
    mkdir $DIR;
fi

echo --------------------
echo - Inizializzazione -
echo --------------------

pdflatex -output-directory=$DIR $NAME
makeglossaries ./$DIR/$NAME.glo
makeglossaries ./$DIR/$NAME.acn
biber $NAME

# Due volte because Latex

pdflatex -output-directory=$DIR $NAME
makeglossaries ./$DIR/$NAME.glo
makeglossaries ./$DIR/$NAME.acn
biber $NAME

echo -------------------------
echo - Generazione Documento -
echo -------------------------

#pdflatex -output-directory=$DIR $NAME
#makeglossaries ./$DIR/$NAME.glo
#makeglossaries ./$DIR/$NAME.acn
#biber $NAME
pdflatex -output-directory=$DIR $NAME
pdflatex -output-directory=$DIR $NAME

echo ---------------------------------
echo - Pulisco e poi apro il file... -
echo ---------------------------------

rm $DIR/*.acn $DIR/*.aux $DIR/*.bbl $DIR/*.bcf $DIR/*.glo $DIR/*.acr $DIR/*.alg
rm $DIR/*.ist $DIR/*.lof $DIR/*.lot $DIR/*.run.xml $DIR/*.toc $DIR/*.glg $DIR/*.gls
# Per mantenere i log commentare la linea seguente
rm $DIR/*.blg  $DIR/*.log

open $DIR/$NAME.pdf

#Rimuovi l'ultima pagina, che è vuota
#pdftk $DIR/$NAME.pdf cat 1-r2 output $DIR/$FINALNAME.pdf

#rm $DIR/$NAME.pdf

echo ---------------------------- END -----------------------------
